### ISSUE TITLE
Assemble problem

### ISSUE THREAD

**Issue by wandering7man** [nsk-mironov/smuggler#19]
faced with issue on windows

```
Caused by: java.lang.IllegalArgumentException: Unable to read a ClassMirror for android/support/design/R$anim
        at io.michaelrocks.grip.ClassRegistryImpl.readClassMirror(ClassRegistry.kt:42)
        at io.michaelrocks.grip.ClassRegistryImpl.getClassMirror(ClassRegistry.kt:21)
        at io.mironov.smuggler.compiler.common.GripExtensionsKt.isSubclassOf(GripExtensions.kt:69)
        at io.mironov.smuggler.compiler.common.GripExtensionsKt$isSubclass$1.invoke(GripExtensions.kt:81)
        at io.mironov.smuggler.compiler.common.GripExtensionsKt$isSubclass$1.invoke(GripExtensions.kt)
        at io.mironov.smuggler.compiler.common.GripExtensionsKt$isGlobalTypeAdapter$$inlined$and$1.invoke(Matchers.kt:27)
        at io.mironov.smuggler.compiler.common.GripExtensionsKt$isGlobalTypeAdapter$$inlined$and$1.invoke(Matchers.kt)
        at io.michaelrocks.grip.ClassesQueryBuilder.execute(ClassesQueryBuilder.kt:28)
        at io.michaelrocks.grip.ClassesQueryBuilder.execute(ClassesQueryBuilder.kt:21)
        at io.michaelrocks.grip.AbstractQueryBuilder$result$1.invoke(AbstractQueryBuilder.kt:31)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:154)
        at io.michaelrocks.grip.AbstractQueryBuilder.execute(AbstractQueryBuilder.kt:55)
        at io.mironov.smuggler.compiler.generators.ValueAdapterFactory$Companion.from(ValueAdapterFactory.kt:64)
        at io.mironov.smuggler.compiler.SmugglerCompiler.compile(SmugglerCompiler.kt:17)
        at io.mironov.smuggler.compiler.SmugglerCompiler$compile.call(Unknown Source)
        at io.mironov.smuggler.plugin.SmugglerTransform.transform(SmugglerTransform.groovy:74)
        at com.android.build.api.transform.Transform.transform(Transform.java:290)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
Caused by: java.lang.IllegalArgumentException: Unable to find a file for android/support/design/R$anim
        at io.michaelrocks.grip.FileRegistryImpl.readClass(FileRegistry.kt:82)
        at io.michaelrocks.grip.ClassRegistryImpl.readClassMirror(ClassRegistry.kt:40)
        ... 95 more
```

**Comment by adelnizamutdinov** [comment]
we're thinking the problem is with Windows' `MAX_PATH` preventing smuggler from generating files (it creates pretty big paths)

**Comment by adelnizamutdinov** [comment]
thanks a lot!
