### ISSUE TITLE
IllegalArgumentException: Unable to read a ClassMirror for android/support/compat/R

### ISSUE THREAD

**Issue by cypressious** [nsk-mironov/smuggler#20]
I've tried adding the plugin to my project and got this when building:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':blsAndroid:transformClassesWithSmugglerForDevMultidexLollipopDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:45)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Error:java.lang.IllegalArgumentException: Unable to read a ClassMirror for android/support/compat/R
	at io.michaelrocks.grip.ClassRegistryImpl.readClassMirror(ClassRegistry.kt:46)
	at io.michaelrocks.grip.ClassRegistryImpl.getClassMirror(ClassRegistry.kt:25)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt.isSubclassOf(GripExtensions.kt:72)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt$isSubclass$1.invoke(GripExtensions.kt:84)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt$isSubclass$1.invoke(GripExtensions.kt)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt$isGlobalTypeAdapter$$inlined$and$1.invoke(Matchers.kt:40)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt$isGlobalTypeAdapter$$inlined$and$1.invoke(Matchers.kt)
	at io.michaelrocks.grip.ClassesQueryBuilder.execute(ClassesQueryBuilder.kt:28)
	at io.michaelrocks.grip.ClassesQueryBuilder.execute(ClassesQueryBuilder.kt:21)
	at io.michaelrocks.grip.AbstractQueryBuilder$result$1.invoke(AbstractQueryBuilder.kt:29)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:154)
	at io.michaelrocks.grip.AbstractQueryBuilder.execute(AbstractQueryBuilder.kt:47)
	at io.mironov.smuggler.compiler.generators.ValueAdapterFactory$Companion.from(ValueAdapterFactory.kt:68)
	at io.mironov.smuggler.compiler.SmugglerCompiler.compile(SmugglerCompiler.kt:17)
	at io.mironov.smuggler.compiler.SmugglerCompiler$compile.call(Unknown Source)
	at io.mironov.smuggler.plugin.SmugglerTransform.transform(SmugglerTransform.groovy:74)
	at com.android.build.api.transform.Transform.transform(Transform.java:290)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 15 more
Error:java.lang.IllegalArgumentException: Unable to find a file for android/support/compat/R
	at io.michaelrocks.grip.FileRegistryImpl.readClass(FileRegistry.kt:85)
	at io.michaelrocks.grip.ClassRegistryImpl.readClassMirror(ClassRegistry.kt:44)
	... 41 more
```

I'm using the smuggler plugin 0.12.8 with Kotlin 1.1-M04 and the android plugin 2.3.0-beta1

**Comment by cypressious** [comment]
Duplicate of https://github.com/nsk-mironov/smuggler/issues/19
