### ISSUE TITLE
Compilation problem 

### ISSUE THREAD

**Issue by emirua** [nsk-mironov/smuggler#36]
I'm having this problem when I try to assemble using v0.14.. Working on windows so It's probably related to this issue https://github.com/nsk-mironov/smuggler/issues/19

```
Caused by: java.lang.IllegalArgumentException: Unable to read a ClassMirror for android/arch/core/util/Function
	at io.michaelrocks.grip.ClassRegistryImpl.readClassMirror(ClassRegistry.kt:46)
	at io.michaelrocks.grip.ClassRegistryImpl.getClassMirror(ClassRegistry.kt:25)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt.isSubclassOf(GripExtensions.kt:54)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt.isSubclassOf(GripExtensions.kt:57)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt$isSubclass$1.invoke(GripExtensions.kt:66)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt$isSubclass$1.invoke(GripExtensions.kt)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt$isGlobalTypeAdapter$$inlined$and$1.invoke(Matchers.kt:40)
	at io.mironov.smuggler.compiler.common.GripExtensionsKt$isGlobalTypeAdapter$$inlined$and$1.invoke(Matchers.kt)
	at io.michaelrocks.grip.ClassesQueryBuilder.execute(ClassesQueryBuilder.kt:28)
	at io.michaelrocks.grip.ClassesQueryBuilder.execute(ClassesQueryBuilder.kt:21)
	at io.michaelrocks.grip.AbstractQueryBuilder$result$1.invoke(AbstractQueryBuilder.kt:29)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at io.michaelrocks.grip.AbstractQueryBuilder.execute(AbstractQueryBuilder.kt:47)
	at io.mironov.smuggler.compiler.generators.ValueAdapterFactory$Companion.from(ValueAdapterFactory.kt:71)
	at io.mironov.smuggler.compiler.SmugglerCompiler.compile(SmugglerCompiler.kt:20)
	at io.mironov.smuggler.plugin.SmugglerTransform.transform(SmugglerTransform.kt:31)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.GeneratedMethodAccessor1578.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 34 more
Caused by: java.lang.IllegalArgumentException: Unable to find a file for android/arch/core/util/Function
	at io.michaelrocks.grip.FileRegistryImpl.readClass(FileRegistry.kt:86)
	at io.michaelrocks.grip.ClassRegistryImpl.readClassMirror(ClassRegistry.kt:44)
	... 68 more

```

**Comment by nsk-mironov** [comment]
Hi, thanks for the report! I'm not really sure what may be a problem here, can you provide the output of the following command `./gradlew dependencies`?

**Comment by emirua** [comment]
Sure! Here are the logs related to the plugin:

```
Analytics other plugin to proto: Unknown plugin type io.mironov.smuggler.plugin.SmugglerPlugin expected enum IO_MIRONOV_SMUGGLER_PLUGIN_SMUGGLERPLUGIN
Analytics other plugin to proto: Unknown plugin type com.android.build.gradle.LibraryPlugin expected enum COM_ANDROID_BUILD_GRADLE_LIBRARYPLUGIN
Analytics other plugin to proto: Unknown plugin type com.android.build.gradle.LibraryPlugin expected enum COM_ANDROID_BUILD_GRADLE_LIBRARYPLUGIN
Analytics other plugin to proto: Unknown plugin type com.android.build.gradle.LibraryPlugin expected enum COM_ANDROID_BUILD_GRADLE_LIBRARYPLUGIN
Analytics other plugin to proto: Unknown plugin type com.android.build.gradle.LibraryPlugin expected enum COM_ANDROID_BUILD_GRADLE_LIBRARYPLUGIN
Analytics other plugin to proto: Unknown plugin type com.android.build.gradle.LibraryPlugin expected enum COM_ANDROID_BUILD_GRADLE_LIBRARYPLUGIN
Analytics other plugin to proto: Unknown plugin type com.android.build.gradle.LibraryPlugin expected enum COM_ANDROID_BUILD_GRADLE_LIBRARYPLUGIN
Analytics other plugin to proto: Unknown plugin type com.android.build.gradle.LibraryPlugin expected enum COM_ANDROID_BUILD_GRADLE_LIBRARYPLUGIN
Analytics other plugin to proto: Unknown plugin type com.android.build.gradle.LibraryPlugin expected enum COM_ANDROID_BUILD_GRADLE_LIBRARYPLUGIN
Analytics other plugin to proto: Unknown plugin type io.mironov.smuggler.plugin.SmugglerPlugin expected enum IO_MIRONOV_SMUGGLER_PLUGIN_SMUGGLERPLUGIN
```

You can find the full log attached
[dependenciesLogSmugglerIssue.txt](https://github.com/nsk-mironov/smuggler/files/2581172/dependenciesLogSmugglerIssue.txt)

Also, this is only happening on Windows since I was able to compile successfully on mac, so it might be related to https://github.com/nsk-mironov/smuggler/issues/19

**Comment by nsk-mironov** [comment]
Sorry, the right command is `./grawdle :yourMainAppModule:dependencies`.

Btw, in case you're starting a new project, it's better not to use this library and use [`@Parcelize`](https://github.com/Kotlin/KEEP/blob/master/proposals/extensions/android-parcelable.md) instead, which is now officially supported by JetBrains.

**Comment by emirua** [comment]
great! Thanks for the suggestion! I'll get back at you with the logs when I'm back on windows :P
